#The rpc address of the chain node
RpcAddr       = ""
#The ip address that the cess-gateway service listens to
ServiceAddr   = ""
#The port number on which the cess-gateway service listens
ServicePort   = ""
#Phrase or seed of for wallet account
AccountSeed   = ""
#Email address
EmailAddress  = ""
#Email password
EmailPassword = ""
#Outgoing server address of SMTP service
EmailHost     = ""
#Outgoing server port number of SMTP service
EmailHostPort = 0