ChainAddr     = "ws://106.15.44.155:9948/"
ServiceAddr   = "localhost"
ServicePort   = "8081"
AccountAddr   = ""
AccountSeed   = "police rent luxury upon furnace above decline fly immune accident cliff pond"
EmailAddress  = ""
EmailPassword = ""